In [1]:
import pandas as pd
from pandas import ExcelWriter
from pandas import ExcelFile
from collections import defaultdict, Counter
import matplotlib.pyplot as plt
from matplotlib import style


import numpy as np
import math

from sklearn import preprocessing, svm
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split, cross_validate
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score
from sklearn import metrics

In [2]:
oddf = pd.read_csv('../data/CDC.csv')

/var/folders/43/8v0k98q97vb38gww2vh96yk00000gn/T/ipykernel_5599/1757297136.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  oddf = pd.read_csv('../data/CDC.csv')

In [3]:
oddf.head()

,Data as of,Year,Month,ST_ABBREV,STATE_NAME,COUNTYNAME,FIPS,STATEFIPS,COUNTYFIPS,CODE2013,Provisional Drug Overdose Deaths,Footnote,Percentage Of Records Pending Investigation,HistoricalDataCompletenessNote,MonthEndingDate,Start Date,End Date
0,7/3/2022,2020,1,AL,Alabama,Autauga,1001,1,1,3,NaN,One or more data cells have counts between 1-9...,0.56,NaN,1/31/2020,1/31/2020,12/31/2021
1,7/3/2022,2020,2,AL,Alabama,Autauga,1001,1,1,3,NaN,One or more data cells have counts between 1-9...,0.55,NaN,2/29/2020,1/31/2020,12/31/2021
2,7/3/2022,2020,3,AL,Alabama,Autauga,1001,1,1,3,NaN,One or more data cells have counts between 1-9...,0.55,NaN,3/31/2020,1/31/2020,12/31/2021
3,7/3/2022,2020,4,AL,Alabama,Autauga,1001,1,1,3,NaN,One or more data cells have counts between 1-9...,0.54,NaN,4/30/2020,1/31/2020,12/31/2021
4,7/3/2022,2020,5,AL,Alabama,Autauga,1001,1,1,3,NaN,One or more data cells have counts between 1-9...,0.54,NaN,5/31/2020,1/31/2020,12/31/2021

In [4]:
oddf['Year'] = oddf['Year'].astype(str)
oddf['Month'] = oddf['Month'].astype(str)

In [5]:
oddf['Date'] = oddf['Month'] + " " + oddf['Year']
oddf['Date'] = pd.to_datetime(oddf['Date'])

In [6]:
oddf = oddf[['STATE_NAME','ST_ABBREV','Date','Year','Month','Provisional Drug Overdose Deaths']]

In [7]:
oddf.head()

  STATE_NAME ST_ABBREV       Date  Year Month Provisional Drug Overdose Deaths
0    Alabama        AL 2020-01-01  2020     1                              NaN
1    Alabama        AL 2020-02-01  2020     2                              NaN
2    Alabama        AL 2020-03-01  2020     3                              NaN
3    Alabama        AL 2020-04-01  2020     4                              NaN
4    Alabama        AL 2020-05-01  2020     5                              NaN